#!/bin/sh

#################################################################
# Stop a commit where an asset or static asset is modified without
# a commensurate update to the manifest file in the dist folder
# which would indicate that new production assets were built and
# the changed assets would also be available in a release.
#

## Check if something changed in one of our asset folders
if git diff --cached --name-only | grep -E --quiet "(assets\/src|assets\/public)"
then
    ASSETS_MODIFIED=true
fi

## Check if the manifest file indicates `npm run build` has been run
if git diff --cached --name-only | grep --quiet "assets/dist/manifest.json"
then
    MANIFEST_MODIFIED=true
fi

if [ -n "$ASSETS_MODIFIED" ] && [ -z "$MANIFEST_MODIFIED" ]; then
    ## If ASSETS have been modified (not null) && MANIFEST has not been modified (is null)
    ## Stop the commit and notify developer to run build script before committing
    echo "Assets modified but not prepared for a release."
    echo "Run production build script before committing."
    exit 1
fi

#################################################################
# Stop a commit that modifies a migration file without also indicating
# that we intentionally want to update the migration file in the commit
# message. This intends to serve as a reminder that changes to migrations
# should usually be handled with new migrations, and that changing old
# migrations can have ripple effects in the chain of migrations.

## Check if something changed in an existing migration files
if git diff --cached --name-only | grep -E --quiet "migrations\/m[0-9]{6}"
then
    MIGRATION_MODIFIED=true
fi

## Check if MIGRATION_MODIFIED is true and the current commit message does not start with the words "Updates migration" or "Adds migration"
if [ -n "$MIGRATION_MODIFIED" ] && ! git log -1 --pretty=%B | grep -q "Adds migration" && ! git log -1 --pretty=%B | grep -q "Updates migration"
then
    echo "Migration modified but not explicit in commit message."
    echo "Start commit message with 'Adds migration...' or 'Updates migration...' to commit this change."
    exit 1
fi




